---
- name: Creation secrets batch
  k8s:
    apply: true
    state: present
    verify_ssl: true
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: batch-secret
        namespace: '{{ jurinorm_namespace }}'
        labels:
          app: '{{ jurinorm_namespace }}'
      type: Opaque
      data:
        S3_ACCESS_KEY: '{{ vault_s3_access_key | b64encode}}'
        S3_SECRET_KEY: '{{ vault_s3_secret_key | b64encode }}'
        DBSDER_API_KEY: '{{ vault_dbsder_api_key | b64encode }}'
        DBSDER_OTHER_API_KEY: '{{ vault_dbsder_other_api_key | b64encode }}'
        DBSDER_POWERFUL_API_KEY: '{{ vault_dbsder_powerful_api_key | b64encode }}'
        AV_PDF_PATH: '{{ vault_av_pdf_path | b64encode }}'
        FILE_DB_URL: '{{ vault_file_db_url | b64encode }}'
