name: jurinorm

services:
  jurinorm:
    build:
      context: ./
    env_file:
      - docker.env
    expose: 
      - 3003
    ports:
      - 3003:3000
    networks: 
      - default
      - dbsder-external-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default
    command: redis-server --appendonly yes
    
networks:
  default:
  dbsder-external-network:
    name: dbsder-external-network

volumes:
  redis_data:
  redisinsight_data:
