---
normalization_batch_schedule: '* * * * *'
commissioning_date_tj: "2023-12-15"
commissioning_date_tcom: "2024-12-31"

s3_access_key: "{{ vault_s3_access_key }}"
s3_secret_key: "{{ vault_s3_secret_key }}"
dbsder_api_key: "{{ vault_dbsder_api_key }}"
dbsder_other_api_key: "{{ vault_dbsder_other_api_key }}"
dbsder_powerful_api_key: "{{ vault_dbsder_powerful_api_key }}"
av_pdf_path: "{{ vault_av_pdf_path }}"
file_db_url: "{{ vault_file_db_url }}"